export const REGISTER_SCENE_ID = 'REGISTER_SCENE';
export const REGISTER_NAME_PROMPT_SCENE = 'REGISTER_NAME_PROMPT_SCENE';
export const QUIZ_SCENE = 'QUIZ_SCENE';
export const REGISTER_PHOTO_SCENE = 'REGISTER_PHOTO_SCENE';
